// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"

	"graffiti/ent/task"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleTask() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the task's edges.

	// create task vertex with its edges.
	t := client.Task.
		Create().
		SetActivity("string").
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetState(task.StateDone).
		SaveX(ctx)
	log.Println("task created:", t)

	// query edges.

	// Output:
}
